# Generated by Django 4.2 on 2023-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSaresp',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('cd_aluno', models.BigIntegerField(blank=True, null=True)),
                ('ano_saresp', models.IntegerField(blank=True, null=True)),
                ('nome_dep', models.CharField(blank=True, max_length=12, null=True)),
                ('mun', models.CharField(blank=True, max_length=15, null=True)),
                ('codesc', models.BigIntegerField(blank=True, null=True)),
                ('escola', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_classe', models.IntegerField(blank=True, null=True)),
                ('serie_ano', models.CharField(blank=True, max_length=255, null=True)),
                ('classe', models.BigIntegerField(blank=True, null=True)),
                ('tp_sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=5, null=True)),
                ('nec_esp_1', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_esp_2', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_esp_3', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_esp_4', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_esp_5', models.CharField(blank=True, max_length=255, null=True)),
                ('tip_prova', models.CharField(blank=True, max_length=1, null=True)),
                ('tem_nec', models.IntegerField(blank=True, null=True)),
                ('cad_prov_lp', models.IntegerField(blank=True, null=True)),
                ('cad_prov_mat', models.IntegerField(blank=True, null=True)),
                ('cad_prov_cie', models.IntegerField(blank=True, null=True)),
                ('particip_lp', models.IntegerField(blank=True, null=True)),
                ('particip_mat', models.IntegerField(blank=True, null=True)),
                ('particip_cie', models.IntegerField(blank=True, null=True)),
                ('total_ponto_lp', models.IntegerField(blank=True, null=True)),
                ('total_ponto_mat', models.IntegerField(blank=True, null=True)),
                ('total_ponto_cie', models.IntegerField(blank=True, null=True)),
                ('porc_cert_lp', models.FloatField(blank=True, null=True)),
                ('porc_cert_mat', models.FloatField(blank=True, null=True)),
                ('porc_cert_cie', models.FloatField(blank=True, null=True)),
                ('profic_lp', models.FloatField(blank=True, null=True)),
                ('profic_mat', models.FloatField(blank=True, null=True)),
                ('profic_cie', models.FloatField(blank=True, null=True)),
                ('nivel_profic_lp', models.CharField(blank=True, max_length=16, null=True)),
                ('nivel_profic_mat', models.CharField(blank=True, max_length=16, null=True)),
                ('nivel_profic_cie', models.CharField(blank=True, max_length=16, null=True)),
                ('classific_lp', models.CharField(blank=True, max_length=12, null=True)),
                ('classific_mat', models.CharField(blank=True, max_length=12, null=True)),
                ('classific_cie', models.CharField(blank=True, max_length=12, null=True)),
                ('validade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dados_saresp',
                'managed': True,
            },
        ),
    ]
